name: Deploy Fullstack VOD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- BACKEND (Mantém Docker no ECR) ---
    - name: Build and Push Backend to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/vod-backend:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/vod-backend:$IMAGE_TAG
    
    # Opcional: Forçar o ECS a baixar a imagem nova imediatamente
    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster vod-cluster --service vod-full-pipeline-BackendService-5dDBEYxvSqpd --force-new-deployment

    # --- FRONTEND (Nova estratégia: S3 + CloudFront) ---
    - name: Build React Frontend
      run: |
        cd frontend
        npm install
        npm run build # Gera a pasta 'build' ou 'dist'

    - name: Sync Files to S3
      run: |
        # Substitui o conteúdo do bucket pelos arquivos novos
        aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET_NAME }} --delete

    - name: Invalidate CloudFront Cache
      run: |
        # Força o CloudFront a atualizar os arquivos para os usuários
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
